#!/bin/bash

exec >cyclictest-server-stop.txt
exec 2>&1

if [ -e stress-ng.pid ]; then
    pid=$(cat stress-ng.pid)
    echo "Going to kill pid ${pid}"
    kill -2 ${pid}
    for i in $(seq 1 10); do
	sleep 3
	echo "."
	if [ ! -e /proc/${pid} ]; then
	    break
	fi
    done
    if [ -e /proc/${pid} ]; then
	echo "PID ${pid} still exists, trying kill -9"
	kill -9 ${pid}

	if [ -e /proc/${pid} ]; then
	    for i in $(seq 1 10); do
		sleep 3
		echo "."
		if [ ! -e /proc/${pid} ]; then
		    echo "PID is gone"
		    break
		fi
	    done
	    if [ -e /proc/${pid} ]; then
		echo "ERROR: PID ${pid} has not been terminated"
		exit 1
	    fi
	fi
    fi
    echo "PID is gone"
else
    echo "stress-ng PID file not found"
    echo "PWD: $(pwd)"
    echo "LS: $(ls)"
    exit 1
fi
