#!/bin/bash
exec >cyclictest-client-stderrout.txt
exec 2>&1

. /usr/bin/cyclictest-base || (echo "/usr/bin/cyclictest-base not found"; exit 1)

dump_runtime
validate_label
validate_sw_prereqs

if [ -z "$WORKLOAD_CPUS" ]; then
    exit_error "WORKLOAD_CPUS is not defined.  This must be defined to run cyclictest"
else
    echo "WORKLOAD_CPUS: $WORKLOAD_CPUS"
fi
if [ -z "$HK_CPUS" ]; then
    exit_error "HK_CPUS is not defined.  This must be defined to run cyclictest"
else
    echo "HK_CPUS: $HK_CPUS"
fi

# defaults
duration=60
policy=fifo
interval=100
smt="on"
break_on=0
smt="on"

longopts="duration:,priority:,policy:,interval:,smt:,break-on:,smi:"
opts=$(getopt -q -o "D:p:i:s:b:" --longoptions "$longopts" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
	--smi)
	    shift
	    smi=$1
	    shift
	    ;;
        -D|--duration)
            shift
            duration=$1
            shift
            ;;
        -p|--priority)
            shift
            priority=$1
            shift
            ;;
        --policy)
            shift
            policy=$1
            shift
            ;;
        -i|--interval)
            shift
            interval=$1
            shift
            ;;
        -s|--smt)
            shift
            smt=$1
            shift
            ;;
	-b|--break-on)
	    shift
	    break_on=$1
	    shift
	    ;;
        --)
            shift;
            break
            ;;
        *)
            shift
            ;;
    esac
done

# adjust CPUs to use
cpu_str=""
for cpu in $(echo $WORKLOAD_CPUS | sed -e "s/,/ /g"); do
    cpu_str+=" --cpu $cpu"
done
cmd="${TOOLBOX_HOME}/bin/get-cpus-ordered.py --smt ${smt} ${cpu_str}"
echo "about to run: ${cmd}"
CMD_OUTPUT=$(${cmd})
echo -e "${CMD_OUTPUT}"
WORKLOAD_CPUS=$(echo -e "${CMD_OUTPUT}" | grep "final cpus:" | awk '{ print $3 }')
echo "WORKLOAD_CPUS: ${WORKLOAD_CPUS}"
WORKLOAD_CPUS_COUNT=$(echo -e "${CMD_OUTPUT}" | grep "final cpus count:" | awk '{ print $4 }')
echo "WORKLOAD_CPUS_COUNT: ${WORKLOAD_CPUS_COUNT}"

cpu_str=""
for cpu in $(echo $HK_CPUS | sed -e "s/,/ /g"); do
    cpu_str+=" --cpu $cpu"
done
cmd="${TOOLBOX_HOME}/bin/get-cpus-ordered.py --smt ${smt} ${cpu_str}"
echo "about to run: ${cmd}"
CMD_OUTPUT=$(${cmd})
echo -e "${CMD_OUTPUT}"
HK_CPUS=$(echo -e "${CMD_OUTPUT}" | grep "final cpus:" | awk '{ print $3 }')
echo "HK_CPUS: ${HK_CPUS}"
HK_CPUS_COUNT=$(echo -e "${CMD_OUTPUT}" | grep "final cpus count:" | awk '{ print $4 }')
echo "HK_CPUS_COUNT: ${HK_CPUS_COUNT}"

prio=""
if [ -n "${priority}" ]; then
    prio="--priority ${priority}"
fi

break=""
if [ ${break_on} -gt 0 ]; then
    break="--breaktrace=${break_on}"
fi

validate_clocksource

case "${smi}" in
    on)
	smi_arg="--smi"
	;;
    off)
	smi_arg=""
	;;
    *)
	exit_error "invalid --smi value [${smi}]"
	;;
esac

cmd="taskset -c ${WORKLOAD_CPUS},${HK_CPUS} /usr/bin/cyclictest --policy $policy ${prio} --interval ${interval} --histofall 100 --histfile histogram.txt --duration ${duration} --quiet --affinity ${WORKLOAD_CPUS} --threads ${WORKLOAD_CPUS_COUNT} --mlockall --json cyclictest.json --mainaffinity ${HK_CPUS} ${smi_arg} ${break}"
echo "About to run: $cmd"
date +%s.%N >begin.txt
$cmd >cyclictest-bin-stderrout.txt 2>&1
rc=$?
date +%s.%N >end.txt

validate_clocksource

if [ $rc -gt 0 ]; then
    exit_error "`cat cyclictest-bin-stderrout.txt`"
fi
    
